### ISSUE TITLE
As a Librarian, I want to checkout item for Patron.( Ravi & Bryce )

### ISSUE THREAD

**Issue by rbf4504** [MIS-565/MIS-565-FrontEnd#12]
Success: 
- system registers the borrowed items with due dates based on the item type
- borrowed items are linked to the patrons account and should be visible to the librarian in their borrowing history 
- loan cap of 20 items is enforced
- automatically disable the theft protection chip on borrowed items
- borrowed items are marked as unavailable in inventory 

Failure: 
- if patrons library card is expired, system rejects the checkout and prompts renewal
- if patron has unpaid fines exceeding the threshold, system rejects checkout and displays a message prompting fine payment
- if item is unavailable, system rejects the checkout and notifies the librarian 
- if borrow limit of 20 items would be exceeded, system rejects checkout and notifies the librarian

**Comment by tnm4414** [comment]
related tasks: #16 #18 #20 #17
