### ISSUE TITLE
As a librarian, I want to validate a patron's library card so only eligible patrons can borrow items.

### ISSUE THREAD

**Issue by rbf4504** [MIS-565/MIS-565-FrontEnd#15]
Success: 
- system confirms the card is valid and not expired (registered in the database and linked to active patron account)
- system checks that card is not expired and allows the checkout process to proceed
- if the card is valid, system checks for outstanding fines or borrowing limit status and confirms eligibility to borrow items

Failure: 
- system shows an error "Card not found" if the card is not found in the database and prompts the librarian to add a new member
- if the card is expired, system displays "Expired membership" and blocks the checkout as well as prompting the librarian to renew
- if patron has unpaid fines, system displays "Borrowing privileges restricted" and provides an explanation why
- if patron already has 20 items checked out, system displays to the librarian "Borrowing limit reached" and the amount of items checked out

**Comment by tnm4414** [comment]
fail case related to #13
