### ISSUE TITLE
Develop the checkout process (Tyler)

### ISSUE THREAD

**Issue by rbf4504** [MIS-565/MIS-565-FrontEnd#16]
Developing a JavaScript code for the checkout activity that has to be part of library management system with all the decisions in place and verifying all the conditions

**Comment by tnm4414** [comment]
User Story #12: As a patron, I want to check out items to use at home.
User Story #15: As a librarian, I want to validate a patron’s library card.
User Story #11: As a librarian, I want the system to calculate overdue fines.
