### ISSUE TITLE
Create a comprehensive document of the library management system(Priyanka)

### ISSUE THREAD

**Issue by SivaM0310** [MIS-565/MIS-565-FrontEnd#63]
As a developer, I am creating a comprehensive document for the Library Management System (LMS) so that stakeholders and developers have a clear understanding of the system's architecture, features, and operational workflows.

Acceptance Criteria:

Document Structure:
The document is structured to include sections like Introduction, System Overview, Use Cases, Database Design, Functional Requirements, Non-Functional Requirements, System Architecture, and Reports.

System Overview:
The system overview provides a high-level description of the LMS, its purpose, and the key functionalities it offers (e.g., patron management, item management, checkout/return processes, fine management, etc.).

Use Cases:
Each use case is clearly defined, including the actors, system interactions, and expected outcomes (e.g., Add Patron, Checkout Items, Return Items, etc.).

**Comment by p2806** [comment]
I had created a comprehensive document which has all details of system Services, Attributes, Git commands, DB connection details.
